### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by naib864** [haideralipunjabi/polybar-kdeconnect#20]
When activating this module, I get an idle cpu usage of 30% on all cores. Not sure why, only thing I'm sure of is that this module is the reason. Would love to find out why, but don't know where and how to look.

EDIT: Happens on both of my Computers, both running Regolith Linux (basically Ubuntu 20.04).

**Comment by haideralipunjabi** [comment]
I will look into it. Meanwhile, what happens if you just use KDEConnect and not my module?

**Comment by naib864** [comment]
KDEConnect itself runs smoothly as far as I can see. I don't use tray icons in my polybar, so it's just running in the background without it's icon.

**Comment by haideralipunjabi** [comment]
I still can't figure out the issue. The only thing I can recommend is removing `tail=true` from the module configuration.  The `tail=true` config executes the script in an infinite loop. Without it, it should refresh every 5 seconds. You can change the refresh interval using the `interval` config.

[Read More](https://github.com/polybar/polybar/wiki/Module:-script)

**Comment by naib864** [comment]
Thanks, will try that. Interesting thing: I only get the High CPU usage on Ubuntu. On Arcolinux CPU usage is fine. But I get an error that it doesn't find the module `org.kde.kdeconnect.device.battery`. Probably an issue with kdeconnect rather than this module, though.

**Comment by haideralipunjabi** [comment]
The couldn't find the module is a new issue due to an update to kdeconnect. I have fixed it yesterday. Use the latest code and it should work fine.

**Comment by naib864** [comment]
Thanks, both things suggested worked, whole script works as intended now :)  
`tail=false` and `interval=1` brings idle cpu usage back to normal.
